import React, { useCallback, useEffect, useState } from 'react'
import Layout from './layout.jsx'
import Head from 'next/head';
import axiosClient from '@/libraries/axiosClient';
import Link from 'next/link';


const Products = ({products})  => {
  return (
    <Layout>
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        products.length > 0 ? (
          <div style={{display: 'flex', flexDirection: 'column'}}>
            {products.map((p) => <Link key={p._id} href={`/products/${p._id}`}><h3>{p.name}</h3></Link>)}
          </div>
        ) : <small>Không có sản phẩm</small>
      }
    </Layout>
  )
}

export default Products;

// getServerSideProps - Server-Side Rendering
export async function getServerSideProps() {
  try {
    const response = await axiosClient.get('/products');

    return {
      props: {
        products: response.data.payload,
      },

      // revalidate: 24 * 60 * 60,
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}

// getStaticProps - Static-Side Generation
// export async function getStaticPaths() {
//   return {
//     paths: [],
//     fallback: true,
//   };
// }

// export async function getStaticProps(req) {
//   try {
//     const response = await axiosClient.get('/products');

//     return {
//       props: {
//         products: response.data.payload,
//       },

//       // revalidate: 10,
//     };
//   } catch (error) {
//     return {
//       notFound: true,
//     };
//   }
// }